version: '3'
services:
  server:
    image: ghazouanihm/movies-server:1.0
    environment:
      - MONGODB_URL=mongodb+srv://ghazouanih68:hm1234@cluster0.kkjjymy.mongodb.net/?retryWrites=true&w=majority
      - PORT=5000
      - TOKEN_SECRET_KEY=hichemghazouani123456
      - TMDB_BASE_URL=https://api.themoviedb.org/3/
      - TMDB_KEY=cdaf399aaa5f1fa9d2dc3d478fa96c06
    ports:
      - 5000:5000


  frontend:
    image: ghazouanihm/movies-front:1.0
    ports:
      - 3000:3000