apiVersion: apps/v1
kind: Deployment
metadata:
  name: moviesserver-deployment
spec:
  selector:
    matchLabels:
      app: moviesserver
  template:
    metadata:
      labels:
        app: moviesserver
    spec:
      containers:
      - name: moviesserver
        image: ghazouanihm/movies-server:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 5000

